trigger:
- master
resources:
- repo: self
variables:
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'sonar'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: sonar-pipeline
        cliProjectName: sonar-pipeline
        
        
    - task: SonarQubeAnalyze@4
    - task: SonarQubePublish@4
      inputs:
        pollingTimeoutSec: '300'
  